config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get 'user/:id/profile', to: 'users/registrations#profile', as: 'user_profile'
    get 'user/:id/account', to: 'users/registrations#account', as: 'user_account'
  end

  resources :subscribes, only: [:index, :new, :create, :show] do
    collection do
      get 'search'
    end
  end

  resources :reserves, only: [:index, :new, :create, :show ]
  post 'reserve/confirm', to: 'reserves#confirm'

  root 'pages#top'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
  mount_uploader :roomphoto, RoomPhotoUploader

  validates :roomname, presence: true
  validates :explanation, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :roomphoto, presence: true

  belongs_to :user
  has_many :reserve
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController
  def new
    @subscribe = Subscribe.new
  end

  def create
    @subscribe = Subscribe.new(params.require(:subscribe).permit(:roomname, :explanation, :price, :address, :roomphoto))
    @subscribe.user_id = current_user.id
    if @subscribe.save
      redirect_to subscribe_path(@subscribe.id)
    else
      render :new
    end
  end

  def index
    @subscribes = Subscribe.all
  end

  def show
    @subscribe = Subscribe.find(params[:id])
  end

  def search
    @subscribes = Subscribe.where('address LIKE ?', "%#{params[:address]}%").where('explanation LIKE ? OR roomname LIKE ?', "%#{params[:keyword]}%", "%#{params[:keyword]}%")
    @result_number = @subscribes.count
  end

  private
  def subscribe_params
    params.require(:subscribe).permit(:roomphoto)
  end
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/views/subscribes/index.html.erb
<div class="container-fiuld subscribe-index">
  <h4 class="pb-4">登録済みルーム一覧</h4>

  <table>
    <thead>
      <tr align="center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>料金</th>
        <th>作成日</th>
      </tr>
    </thead>

    <tbody>
      <% @subscribes.each do |subscribe| %>
        <% if subscribe.user_id == current_user.id %>
          <tr>
            <td>
              <%= link_to subscribe_path(subscribe.id) do %>
                <%= image_tag subscribe.roomphoto.thumb.url, alt: "部屋画像", class: "subscribe-index-image" %>
              <% end %>
            </td>
          
            <td class="subscribe-roomname"><%= link_to subscribe.roomname, subscribe_path(subscribe.id) %></td>
            <td class="subscribe-explanation"><%= subscribe.explanation %></td>
            <td class="price-icon"><%= subscribe.price %></td>
            <td><%= subscribe.created_at %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div class="push-footer"></div>
</div>

app/views/subscribes/new.html.erb
<div class="container-fiuld subscribe-new">
  <div class="row">
    <div class="col-lg-2 subscribe-nav subscribe-nav-pc d-lg-block d-none">
      <ul>
        <li class="active">
          <%= link_to "基本情報", new_subscribe_path %>
        </li>
      </ul>
    </div>

    <div class="col-lg-2 subscribe-nav subscribe-nav-mobile d-lg-none">
      <ul>
        <li class="active">
          <%= link_to "基本情報", new_subscribe_path %>
        </li>
      </ul>
    </div>

    <div class="col-lg-10 subscribe-view">
      <div class="subscribe-view-box">
        <%= form_with model: @subscribe, id: 'new_subscribe', class: 'new_subscribe', local: true do |f| %>

          <div class="update-content">
            <div class="row">
              <h5>ルーム情報登録</h5>
            </div>
          </div>
        
          <div class="update-content">
            <div class="row">
              <label for="roomname", class="col-md-3 required-a">
                ルーム名
              </label>
              <%= f.text_field :roomname, placeholder: "ルーム名を入力", autocomplete: "subscribe_roomname", class: "form-controll mb-4 col-md-9" %>
            </div>
          </div>

          <div class="update-content">
            <div class="row">
              <label for="explanation", class="col-md-3 required-a">
                ルーム紹介
              </label>
              <%= f.text_field :explanation, placeholder: "ルーム説明を入力", autocomplete: "subscribe_explanation", class: "form-controll mb-4 col-md-9", row: "5" %>
            </div>
          </div>

          <div class="update-content">
            <div class="row">
              <label for="price", class="col-md-3 required-a">
                料金
              </label>
              <%= f.number_field :price, placeholder: "一日あたりの料金を入力", autocomplete: "subscribe_price", class: "form-controll mb-4 col-md-9" %>
            </div>
          </div>

          <div class="update-content">
            <div class="row">
              <label for="address", class="col-md-3 required-a">
                住所
              </label>
              <%= f.text_field :address, placeholder: "住所を入力", autocomplete: "subscribe_address", class: "form-control mb-4 col-md-9" %>
            </div>
          </div>

          <div class="update-content">
            <div class="row">
              <label for="roomphoto", class="col-md-3 required-a" >
                ルーム画像
              </label>
              <%= f.file_field :roomphoto, placeholder: "ルーム画像をアップロード", autocomplete: "subscribe_room_photo", class: "mb-4 col-md-9" %>
            </div>
          </div>

          <%= f.hidden_field :user_id, value: current_user.id %>

          <div class="update-content">
            <div class="row">
              <%= f.submit "登録", class: "col-md-2 btn btn-primary mx-3", data: {disable_with: "登録"} %>
            </div>
          </div>
        <% end %>       
      </div>
    </div>
  </div>
</div>

app/views/subscribes/search.html.erb
<div class="container-fiuld subscribe">
  <h4 class="pb-4">検索結果：<%= @result_number %>件</h4>
  <div class="row">

    <% @subscribes.each do |subscribe| %>
      <div class="col-sm-6 col-lg-4 col-xl-3">
        <div class="subscribe-frame-inner">
          <%= link_to(controller: 'subscribes', action: 'show', id: subscribe.id) do %>
            <div class="subscribe-roomphoto-out">
              <%= image_tag subscribe.roomphoto.url, alt: "部屋画像", class: "subscribe-roomphoto" %>
            </div>

            <div class="subscribe-profile">
              <p class="subscribe-profile-roomname"><%= subscribe.roomname %></p>
              <p class="subscribe-profile-address"><%= subscribe.address %></p>
              <p class="subscribe-profile-price price-icon"><%= subscribe.price %></p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="push-footer"></div>
</div>

app/views/subscribes/show.html.erb
<div class="container subscribe-show">
  <div class="row">
    <div class="col-md-8">
      <%= image_tag @subscribe.roomphoto.url, alt: "部屋画像", class: "subscribe-show-image" %>
      <div class="subscribe-show-detail">
        <div class="subscribe-show-detail-icon">
          <%= link_to root_path do %>
            <img class="host-icon" src="/assets/default_icon.jpg" >
          <% end %>
        </div>

        <div class="subscribe-show-profile">
          <p class="subscribe-show-profile-name"><%= @subscribe.roomname %></p>
          <p class="subscribe-show-profile-address"><%= @subscribe.address %></p>
        </div>
      </div>

      <p class="subscribe-show-detail-content"><%= @subscribe.explanation %></p>
    </div>

    <div class="col-md-4">
      <div class="subscribe-show-nav">
        <h5 class="price-icon"><%= @subscribe.price %> / 日</h5>
        <div class="subscribe-show-date-select">
          <%= form_with url: reserve_confirm_path, local: true do |f| %>
            <%= f.hidden_field :subscribe_id, value: @subscribe.id %>
            <%= f.hidden_field :user_id, value: current_user.id %>

            <label for="start-date">開始日</label>
            <%= f.date_field :start_date, class: "form-control mb-4" %>
            <label for="end-date">終了日</label>
            <%= f.date_field :end_date, class: "form-control mb-4" %>
            <label for="number_of_people">人数</label>
            <%= f.number_field :headcount, class: "form-control mb-4" %>

            <% if user_signed_in? %>
              <%= f.submit "予約する", class: "btn btn-primary form-control", data: {disable_with: "予約する"} %>
            <% else %>
              <%= link_to "ログイン", session_new_path, class: "btn btn-primary form-control" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>